# Has to mirror the config in docker-compose.yml.
database:
  host: localhost
  port: 5432
  user: devUser
  password: devPassword
  dbname: easypark
  sslmode: disable

httpserver:
  address: :8081

auth:
  secretkey: whatever

logging:
  level: info
  gormlevel: error