# Has to mirror the config in docker-compose.yml.
database:
  host: localhost
  port: 5432
  user: devUser
  password: devPassword
  dbname: easypark
  sslmode: disable

http:
  address: :8080

auth:
  secretkey: whatever

logging:
  level: debug
  gormlevel: error
  format: text

scheduler:
  interval: "*/5 * * * *" # Every 5 minutes.

alert:
  LateArrivalThresholdMinutes: "60m" # 60 minutes.