version: "3.8"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=devUser
      - POSTGRES_PASSWORD=devPassword
      - POSTGRES_DB=easypark
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - database
volumes:
  db: