// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MessageFacade is an autogenerated mock type for the MessageFacade type
type MessageFacade struct {
	mock.Mock
}

type MessageFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageFacade) EXPECT() *MessageFacade_Expecter {
	return &MessageFacade_Expecter{mock: &_m.Mock}
}

// DequeueMessages provides a mock function with given fields: ctx, userID
func (_m *MessageFacade) DequeueMessages(ctx context.Context, userID uuid.UUID) ([]entities.Message, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DequeueMessages")
	}

	var r0 []entities.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entities.Message, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entities.Message); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageFacade_DequeueMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DequeueMessages'
type MessageFacade_DequeueMessages_Call struct {
	*mock.Call
}

// DequeueMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MessageFacade_Expecter) DequeueMessages(ctx interface{}, userID interface{}) *MessageFacade_DequeueMessages_Call {
	return &MessageFacade_DequeueMessages_Call{Call: _e.mock.On("DequeueMessages", ctx, userID)}
}

func (_c *MessageFacade_DequeueMessages_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MessageFacade_DequeueMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MessageFacade_DequeueMessages_Call) Return(_a0 []entities.Message, _a1 error) *MessageFacade_DequeueMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageFacade_DequeueMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entities.Message, error)) *MessageFacade_DequeueMessages_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueMessage provides a mock function with given fields: ctx, senderID, receiverID, content
func (_m *MessageFacade) EnqueueMessage(ctx context.Context, senderID uuid.UUID, receiverID uuid.UUID, content string) (entities.Message, error) {
	ret := _m.Called(ctx, senderID, receiverID, content)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueMessage")
	}

	var r0 entities.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (entities.Message, error)); ok {
		return rf(ctx, senderID, receiverID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) entities.Message); ok {
		r0 = rf(ctx, senderID, receiverID, content)
	} else {
		r0 = ret.Get(0).(entities.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, senderID, receiverID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageFacade_EnqueueMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueMessage'
type MessageFacade_EnqueueMessage_Call struct {
	*mock.Call
}

// EnqueueMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - receiverID uuid.UUID
//   - content string
func (_e *MessageFacade_Expecter) EnqueueMessage(ctx interface{}, senderID interface{}, receiverID interface{}, content interface{}) *MessageFacade_EnqueueMessage_Call {
	return &MessageFacade_EnqueueMessage_Call{Call: _e.mock.On("EnqueueMessage", ctx, senderID, receiverID, content)}
}

func (_c *MessageFacade_EnqueueMessage_Call) Run(run func(ctx context.Context, senderID uuid.UUID, receiverID uuid.UUID, content string)) *MessageFacade_EnqueueMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MessageFacade_EnqueueMessage_Call) Return(_a0 entities.Message, _a1 error) *MessageFacade_EnqueueMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageFacade_EnqueueMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (entities.Message, error)) *MessageFacade_EnqueueMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageFacade creates a new instance of MessageFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageFacade {
	mock := &MessageFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
