// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// RequestAuthoriser is an autogenerated mock type for the RequestAuthoriser type
type RequestAuthoriser struct {
	mock.Mock
}

type RequestAuthoriser_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestAuthoriser) EXPECT() *RequestAuthoriser_Expecter {
	return &RequestAuthoriser_Expecter{mock: &_m.Mock}
}

// Authorise provides a mock function with given fields: next
func (_m *RequestAuthoriser) Authorise(next http.Handler) http.Handler {
	ret := _m.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for Authorise")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// RequestAuthoriser_Authorise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorise'
type RequestAuthoriser_Authorise_Call struct {
	*mock.Call
}

// Authorise is a helper method to define mock.On call
//   - next http.Handler
func (_e *RequestAuthoriser_Expecter) Authorise(next interface{}) *RequestAuthoriser_Authorise_Call {
	return &RequestAuthoriser_Authorise_Call{Call: _e.mock.On("Authorise", next)}
}

func (_c *RequestAuthoriser_Authorise_Call) Run(run func(next http.Handler)) *RequestAuthoriser_Authorise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *RequestAuthoriser_Authorise_Call) Return(_a0 http.Handler) *RequestAuthoriser_Authorise_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestAuthoriser_Authorise_Call) RunAndReturn(run func(http.Handler) http.Handler) *RequestAuthoriser_Authorise_Call {
	_c.Call.Return(run)
	return _c
}

// RequireRole provides a mock function with given fields: requiredRole
func (_m *RequestAuthoriser) RequireRole(requiredRole entities.UserRole) func(http.Handler) http.Handler {
	ret := _m.Called(requiredRole)

	if len(ret) == 0 {
		panic("no return value specified for RequireRole")
	}

	var r0 func(http.Handler) http.Handler
	if rf, ok := ret.Get(0).(func(entities.UserRole) func(http.Handler) http.Handler); ok {
		r0 = rf(requiredRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}

	return r0
}

// RequestAuthoriser_RequireRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireRole'
type RequestAuthoriser_RequireRole_Call struct {
	*mock.Call
}

// RequireRole is a helper method to define mock.On call
//   - requiredRole entities.UserRole
func (_e *RequestAuthoriser_Expecter) RequireRole(requiredRole interface{}) *RequestAuthoriser_RequireRole_Call {
	return &RequestAuthoriser_RequireRole_Call{Call: _e.mock.On("RequireRole", requiredRole)}
}

func (_c *RequestAuthoriser_RequireRole_Call) Run(run func(requiredRole entities.UserRole)) *RequestAuthoriser_RequireRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.UserRole))
	})
	return _c
}

func (_c *RequestAuthoriser_RequireRole_Call) Return(_a0 func(http.Handler) http.Handler) *RequestAuthoriser_RequireRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestAuthoriser_RequireRole_Call) RunAndReturn(run func(entities.UserRole) func(http.Handler) http.Handler) *RequestAuthoriser_RequireRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewRequestAuthoriser creates a new instance of RequestAuthoriser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestAuthoriser(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestAuthoriser {
	mock := &RequestAuthoriser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
