// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MessageDequeuer is an autogenerated mock type for the MessageDequeuer type
type MessageDequeuer struct {
	mock.Mock
}

type MessageDequeuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageDequeuer) EXPECT() *MessageDequeuer_Expecter {
	return &MessageDequeuer_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID
func (_m *MessageDequeuer) Execute(ctx context.Context, userID uuid.UUID) ([]entities.Message, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entities.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entities.Message, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entities.Message); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageDequeuer_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MessageDequeuer_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MessageDequeuer_Expecter) Execute(ctx interface{}, userID interface{}) *MessageDequeuer_Execute_Call {
	return &MessageDequeuer_Execute_Call{Call: _e.mock.On("Execute", ctx, userID)}
}

func (_c *MessageDequeuer_Execute_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MessageDequeuer_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MessageDequeuer_Execute_Call) Return(_a0 []entities.Message, _a1 error) *MessageDequeuer_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageDequeuer_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entities.Message, error)) *MessageDequeuer_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageDequeuer creates a new instance of MessageDequeuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageDequeuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageDequeuer {
	mock := &MessageDequeuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
