// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ParkingRequestAutomaticSpaceAssigner is an autogenerated mock type for the ParkingRequestAutomaticSpaceAssigner type
type ParkingRequestAutomaticSpaceAssigner struct {
	mock.Mock
}

type ParkingRequestAutomaticSpaceAssigner_Expecter struct {
	mock *mock.Mock
}

func (_m *ParkingRequestAutomaticSpaceAssigner) EXPECT() *ParkingRequestAutomaticSpaceAssigner_Expecter {
	return &ParkingRequestAutomaticSpaceAssigner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, requestID
func (_m *ParkingRequestAutomaticSpaceAssigner) Execute(ctx context.Context, requestID uuid.UUID) (*entities.ParkingSpace, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.ParkingSpace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.ParkingSpace, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.ParkingSpace); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ParkingSpace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParkingRequestAutomaticSpaceAssigner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ParkingRequestAutomaticSpaceAssigner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *ParkingRequestAutomaticSpaceAssigner_Expecter) Execute(ctx interface{}, requestID interface{}) *ParkingRequestAutomaticSpaceAssigner_Execute_Call {
	return &ParkingRequestAutomaticSpaceAssigner_Execute_Call{Call: _e.mock.On("Execute", ctx, requestID)}
}

func (_c *ParkingRequestAutomaticSpaceAssigner_Execute_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *ParkingRequestAutomaticSpaceAssigner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ParkingRequestAutomaticSpaceAssigner_Execute_Call) Return(_a0 *entities.ParkingSpace, _a1 error) *ParkingRequestAutomaticSpaceAssigner_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParkingRequestAutomaticSpaceAssigner_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entities.ParkingSpace, error)) *ParkingRequestAutomaticSpaceAssigner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewParkingRequestAutomaticSpaceAssigner creates a new instance of ParkingRequestAutomaticSpaceAssigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingRequestAutomaticSpaceAssigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingRequestAutomaticSpaceAssigner {
	mock := &ParkingRequestAutomaticSpaceAssigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
