// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ParkingRequestDriversGetter is an autogenerated mock type for the ParkingRequestDriversGetter type
type ParkingRequestDriversGetter struct {
	mock.Mock
}

type ParkingRequestDriversGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *ParkingRequestDriversGetter) EXPECT() *ParkingRequestDriversGetter_Expecter {
	return &ParkingRequestDriversGetter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id
func (_m *ParkingRequestDriversGetter) Execute(ctx context.Context, id uuid.UUID) ([]entities.ParkingRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []entities.ParkingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entities.ParkingRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entities.ParkingRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.ParkingRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParkingRequestDriversGetter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ParkingRequestDriversGetter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ParkingRequestDriversGetter_Expecter) Execute(ctx interface{}, id interface{}) *ParkingRequestDriversGetter_Execute_Call {
	return &ParkingRequestDriversGetter_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *ParkingRequestDriversGetter_Execute_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ParkingRequestDriversGetter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ParkingRequestDriversGetter_Execute_Call) Return(_a0 []entities.ParkingRequest, _a1 error) *ParkingRequestDriversGetter_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParkingRequestDriversGetter_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entities.ParkingRequest, error)) *ParkingRequestDriversGetter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewParkingRequestDriversGetter creates a new instance of ParkingRequestDriversGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingRequestDriversGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingRequestDriversGetter {
	mock := &ParkingRequestDriversGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
