// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ParkingRequestSpaceDeassigner is an autogenerated mock type for the ParkingRequestSpaceDeassigner type
type ParkingRequestSpaceDeassigner struct {
	mock.Mock
}

type ParkingRequestSpaceDeassigner_Expecter struct {
	mock *mock.Mock
}

func (_m *ParkingRequestSpaceDeassigner) EXPECT() *ParkingRequestSpaceDeassigner_Expecter {
	return &ParkingRequestSpaceDeassigner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, requestID
func (_m *ParkingRequestSpaceDeassigner) Execute(ctx context.Context, requestID uuid.UUID) error {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParkingRequestSpaceDeassigner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ParkingRequestSpaceDeassigner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *ParkingRequestSpaceDeassigner_Expecter) Execute(ctx interface{}, requestID interface{}) *ParkingRequestSpaceDeassigner_Execute_Call {
	return &ParkingRequestSpaceDeassigner_Execute_Call{Call: _e.mock.On("Execute", ctx, requestID)}
}

func (_c *ParkingRequestSpaceDeassigner_Execute_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *ParkingRequestSpaceDeassigner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ParkingRequestSpaceDeassigner_Execute_Call) Return(_a0 error) *ParkingRequestSpaceDeassigner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ParkingRequestSpaceDeassigner_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ParkingRequestSpaceDeassigner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewParkingRequestSpaceDeassigner creates a new instance of ParkingRequestSpaceDeassigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingRequestSpaceDeassigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingRequestSpaceDeassigner {
	mock := &ParkingRequestSpaceDeassigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
