// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ParkingSpaceGetter is an autogenerated mock type for the ParkingSpaceGetter type
type ParkingSpaceGetter struct {
	mock.Mock
}

type ParkingSpaceGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *ParkingSpaceGetter) EXPECT() *ParkingSpaceGetter_Expecter {
	return &ParkingSpaceGetter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, parkingSpaceID
func (_m *ParkingSpaceGetter) Execute(ctx context.Context, parkingSpaceID uuid.UUID) (entities.ParkingSpace, error) {
	ret := _m.Called(ctx, parkingSpaceID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entities.ParkingSpace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entities.ParkingSpace, error)); ok {
		return rf(ctx, parkingSpaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entities.ParkingSpace); ok {
		r0 = rf(ctx, parkingSpaceID)
	} else {
		r0 = ret.Get(0).(entities.ParkingSpace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, parkingSpaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParkingSpaceGetter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ParkingSpaceGetter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - parkingSpaceID uuid.UUID
func (_e *ParkingSpaceGetter_Expecter) Execute(ctx interface{}, parkingSpaceID interface{}) *ParkingSpaceGetter_Execute_Call {
	return &ParkingSpaceGetter_Execute_Call{Call: _e.mock.On("Execute", ctx, parkingSpaceID)}
}

func (_c *ParkingSpaceGetter_Execute_Call) Run(run func(ctx context.Context, parkingSpaceID uuid.UUID)) *ParkingSpaceGetter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ParkingSpaceGetter_Execute_Call) Return(_a0 entities.ParkingSpace, _a1 error) *ParkingSpaceGetter_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParkingSpaceGetter_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entities.ParkingSpace, error)) *ParkingSpaceGetter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewParkingSpaceGetter creates a new instance of ParkingSpaceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingSpaceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingSpaceGetter {
	mock := &ParkingSpaceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
