// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ParkingSpaceStatusUpdater is an autogenerated mock type for the ParkingSpaceStatusUpdater type
type ParkingSpaceStatusUpdater struct {
	mock.Mock
}

type ParkingSpaceStatusUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *ParkingSpaceStatusUpdater) EXPECT() *ParkingSpaceStatusUpdater_Expecter {
	return &ParkingSpaceStatusUpdater_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id, status
func (_m *ParkingSpaceStatusUpdater) Execute(ctx context.Context, id uuid.UUID, status string) (entities.ParkingSpace, error) {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entities.ParkingSpace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (entities.ParkingSpace, error)); ok {
		return rf(ctx, id, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) entities.ParkingSpace); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Get(0).(entities.ParkingSpace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParkingSpaceStatusUpdater_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ParkingSpaceStatusUpdater_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
func (_e *ParkingSpaceStatusUpdater_Expecter) Execute(ctx interface{}, id interface{}, status interface{}) *ParkingSpaceStatusUpdater_Execute_Call {
	return &ParkingSpaceStatusUpdater_Execute_Call{Call: _e.mock.On("Execute", ctx, id, status)}
}

func (_c *ParkingSpaceStatusUpdater_Execute_Call) Run(run func(ctx context.Context, id uuid.UUID, status string)) *ParkingSpaceStatusUpdater_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ParkingSpaceStatusUpdater_Execute_Call) Return(_a0 entities.ParkingSpace, _a1 error) *ParkingSpaceStatusUpdater_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParkingSpaceStatusUpdater_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (entities.ParkingSpace, error)) *ParkingSpaceStatusUpdater_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewParkingSpaceStatusUpdater creates a new instance of ParkingSpaceStatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingSpaceStatusUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingSpaceStatusUpdater {
	mock := &ParkingSpaceStatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
