// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// UserCreator is an autogenerated mock type for the UserCreator type
type UserCreator struct {
	mock.Mock
}

type UserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCreator) EXPECT() *UserCreator_Expecter {
	return &UserCreator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, user
func (_m *UserCreator) Execute(ctx context.Context, user *entities.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCreator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UserCreator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *UserCreator_Expecter) Execute(ctx interface{}, user interface{}) *UserCreator_Execute_Call {
	return &UserCreator_Execute_Call{Call: _e.mock.On("Execute", ctx, user)}
}

func (_c *UserCreator_Execute_Call) Run(run func(ctx context.Context, user *entities.User)) *UserCreator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.User))
	})
	return _c
}

func (_c *UserCreator_Execute_Call) Return(_a0 error) *UserCreator_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserCreator_Execute_Call) RunAndReturn(run func(context.Context, *entities.User) error) *UserCreator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserCreator creates a new instance of UserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCreator {
	mock := &UserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
