// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserFacade is an autogenerated mock type for the UserFacade type
type UserFacade struct {
	mock.Mock
}

type UserFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *UserFacade) EXPECT() *UserFacade_Expecter {
	return &UserFacade_Expecter{mock: &_m.Mock}
}

// AuthoriseUser provides a mock function with given fields: ctx, username, password
func (_m *UserFacade) AuthoriseUser(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthoriseUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserFacade_AuthoriseUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthoriseUser'
type UserFacade_AuthoriseUser_Call struct {
	*mock.Call
}

// AuthoriseUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *UserFacade_Expecter) AuthoriseUser(ctx interface{}, username interface{}, password interface{}) *UserFacade_AuthoriseUser_Call {
	return &UserFacade_AuthoriseUser_Call{Call: _e.mock.On("AuthoriseUser", ctx, username, password)}
}

func (_c *UserFacade_AuthoriseUser_Call) Run(run func(ctx context.Context, username string, password string)) *UserFacade_AuthoriseUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserFacade_AuthoriseUser_Call) Return(_a0 string, _a1 error) *UserFacade_AuthoriseUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserFacade_AuthoriseUser_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *UserFacade_AuthoriseUser_Call {
	_c.Call.Return(run)
	return _c
}

// BanDriver provides a mock function with given fields: ctx, id
func (_m *UserFacade) BanDriver(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BanDriver")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserFacade_BanDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanDriver'
type UserFacade_BanDriver_Call struct {
	*mock.Call
}

// BanDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserFacade_Expecter) BanDriver(ctx interface{}, id interface{}) *UserFacade_BanDriver_Call {
	return &UserFacade_BanDriver_Call{Call: _e.mock.On("BanDriver", ctx, id)}
}

func (_c *UserFacade_BanDriver_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserFacade_BanDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserFacade_BanDriver_Call) Return(_a0 error) *UserFacade_BanDriver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserFacade_BanDriver_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *UserFacade_BanDriver_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDriver provides a mock function with given fields: ctx, driver
func (_m *UserFacade) CreateDriver(ctx context.Context, driver *entities.User) (*entities.User, error) {
	ret := _m.Called(ctx, driver)

	if len(ret) == 0 {
		panic("no return value specified for CreateDriver")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) (*entities.User, error)); ok {
		return rf(ctx, driver)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) *entities.User); ok {
		r0 = rf(ctx, driver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.User) error); ok {
		r1 = rf(ctx, driver)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserFacade_CreateDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDriver'
type UserFacade_CreateDriver_Call struct {
	*mock.Call
}

// CreateDriver is a helper method to define mock.On call
//   - ctx context.Context
//   - driver *entities.User
func (_e *UserFacade_Expecter) CreateDriver(ctx interface{}, driver interface{}) *UserFacade_CreateDriver_Call {
	return &UserFacade_CreateDriver_Call{Call: _e.mock.On("CreateDriver", ctx, driver)}
}

func (_c *UserFacade_CreateDriver_Call) Run(run func(ctx context.Context, driver *entities.User)) *UserFacade_CreateDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.User))
	})
	return _c
}

func (_c *UserFacade_CreateDriver_Call) Return(_a0 *entities.User, _a1 error) *UserFacade_CreateDriver_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserFacade_CreateDriver_Call) RunAndReturn(run func(context.Context, *entities.User) (*entities.User, error)) *UserFacade_CreateDriver_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDriverUsers provides a mock function with given fields: ctx
func (_m *UserFacade) GetAllDriverUsers(ctx context.Context) ([]entities.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDriverUsers")
	}

	var r0 []entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserFacade_GetAllDriverUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDriverUsers'
type UserFacade_GetAllDriverUsers_Call struct {
	*mock.Call
}

// GetAllDriverUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserFacade_Expecter) GetAllDriverUsers(ctx interface{}) *UserFacade_GetAllDriverUsers_Call {
	return &UserFacade_GetAllDriverUsers_Call{Call: _e.mock.On("GetAllDriverUsers", ctx)}
}

func (_c *UserFacade_GetAllDriverUsers_Call) Run(run func(ctx context.Context)) *UserFacade_GetAllDriverUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserFacade_GetAllDriverUsers_Call) Return(_a0 []entities.User, _a1 error) *UserFacade_GetAllDriverUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserFacade_GetAllDriverUsers_Call) RunAndReturn(run func(context.Context) ([]entities.User, error)) *UserFacade_GetAllDriverUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserFacade creates a new instance of UserFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserFacade {
	mock := &UserFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
