// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserFacade is an autogenerated mock type for the UserFacade type
type UserFacade struct {
	mock.Mock
}

type UserFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *UserFacade) EXPECT() *UserFacade_Expecter {
	return &UserFacade_Expecter{mock: &_m.Mock}
}

// AuthoriseUser provides a mock function with given fields: ctx, username, password
func (_m *UserFacade) AuthoriseUser(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthoriseUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserFacade_AuthoriseUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthoriseUser'
type UserFacade_AuthoriseUser_Call struct {
	*mock.Call
}

// AuthoriseUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *UserFacade_Expecter) AuthoriseUser(ctx interface{}, username interface{}, password interface{}) *UserFacade_AuthoriseUser_Call {
	return &UserFacade_AuthoriseUser_Call{Call: _e.mock.On("AuthoriseUser", ctx, username, password)}
}

func (_c *UserFacade_AuthoriseUser_Call) Run(run func(ctx context.Context, username string, password string)) *UserFacade_AuthoriseUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserFacade_AuthoriseUser_Call) Return(_a0 string, _a1 error) *UserFacade_AuthoriseUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserFacade_AuthoriseUser_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *UserFacade_AuthoriseUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, driver
func (_m *UserFacade) CreateUser(ctx context.Context, driver *entities.User) error {
	ret := _m.Called(ctx, driver)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, driver)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserFacade_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserFacade_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - driver *entities.User
func (_e *UserFacade_Expecter) CreateUser(ctx interface{}, driver interface{}) *UserFacade_CreateUser_Call {
	return &UserFacade_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, driver)}
}

func (_c *UserFacade_CreateUser_Call) Run(run func(ctx context.Context, driver *entities.User)) *UserFacade_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.User))
	})
	return _c
}

func (_c *UserFacade_CreateUser_Call) Return(_a0 error) *UserFacade_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserFacade_CreateUser_Call) RunAndReturn(run func(context.Context, *entities.User) error) *UserFacade_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserFacade creates a new instance of UserFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserFacade {
	mock := &UserFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
