// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// DBHandler is an autogenerated mock type for the DBHandler type
type DBHandler struct {
	mock.Mock
}

type DBHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *DBHandler) EXPECT() *DBHandler_Expecter {
	return &DBHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, value
func (_m *DBHandler) Create(ctx context.Context, value interface{}) *gorm.DB {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) *gorm.DB); ok {
		r0 = rf(ctx, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// DBHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DBHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *DBHandler_Expecter) Create(ctx interface{}, value interface{}) *DBHandler_Create_Call {
	return &DBHandler_Create_Call{Call: _e.mock.On("Create", ctx, value)}
}

func (_c *DBHandler_Create_Call) Run(run func(ctx context.Context, value interface{})) *DBHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *DBHandler_Create_Call) Return(_a0 *gorm.DB) *DBHandler_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBHandler_Create_Call) RunAndReturn(run func(context.Context, interface{}) *gorm.DB) *DBHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBHandler creates a new instance of DBHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBHandler {
	mock := &DBHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
