// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/IgorSteps/easypark/internal/adapters/websocket/handlers"
	"github.com/IgorSteps/easypark/internal/adapters/websocket/routes"
	"github.com/IgorSteps/easypark/internal/drivers/config"
	"github.com/IgorSteps/easypark/internal/drivers/logger"
	"github.com/IgorSteps/easypark/internal/drivers/websocketserver"
)

// Injectors from wire.go:

func SetupApp() (*App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	loggingConfig := configConfig.Logging
	logrusLogger := logger.NewLoggerFromConfig(loggingConfig)
	hub := handlers.NewHub(logrusLogger)
	router := routes.NewRouter(logrusLogger, hub)
	httpConfig := configConfig.HTTP
	server := websocketserver.NewServerFromConfig(router, httpConfig, logrusLogger)
	app := NewApp(server, logrusLogger, hub)
	return app, nil
}
