# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Easypark CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:latest
        # Same as in docker-compose file
        env:
          POSTGRES_USER: devUser
          POSTGRES_PASSWORD: devPassword
          POSTGRES_DB: easypark
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: make build

    - name: Unit Test
      run: make unit
    
    - name: Wait for PostgreSQL
      run: until pg_isready -h localhost -p 5432; do sleep 1; done

    - name: Functional Tests
      run: |
        make run &
        APP_PID=$!
        make run-ws &
        WS_PID=$!
        sleep 5
        make functional
        kill $APP_PID
        kill $WS_PID
