// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/IgorSteps/easypark/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CheckUserExists provides a mock function with given fields: ctx, email, uname
func (_m *UserRepository) CheckUserExists(ctx context.Context, email string, uname string) (bool, error) {
	ret := _m.Called(ctx, email, uname)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, email, uname)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, email, uname)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, uname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_CheckUserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserExists'
type UserRepository_CheckUserExists_Call struct {
	*mock.Call
}

// CheckUserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - uname string
func (_e *UserRepository_Expecter) CheckUserExists(ctx interface{}, email interface{}, uname interface{}) *UserRepository_CheckUserExists_Call {
	return &UserRepository_CheckUserExists_Call{Call: _e.mock.On("CheckUserExists", ctx, email, uname)}
}

func (_c *UserRepository_CheckUserExists_Call) Run(run func(ctx context.Context, email string, uname string)) *UserRepository_CheckUserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_CheckUserExists_Call) Return(_a0 bool, _a1 error) *UserRepository_CheckUserExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_CheckUserExists_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *UserRepository_CheckUserExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserRepository) CreateUser(ctx context.Context, user *entities.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *UserRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *UserRepository_CreateUser_Call {
	return &UserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UserRepository_CreateUser_Call) Run(run func(ctx context.Context, user *entities.User)) *UserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.User))
	})
	return _c
}

func (_c *UserRepository_CreateUser_Call) Return(_a0 error) *UserRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *entities.User) error) *UserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepository) FindByUsername(ctx context.Context, username string) (*entities.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type UserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserRepository_Expecter) FindByUsername(ctx interface{}, username interface{}) *UserRepository_FindByUsername_Call {
	return &UserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *UserRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *UserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_FindByUsername_Call) Return(_a0 *entities.User, _a1 error) *UserRepository_FindByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_FindByUsername_Call) RunAndReturn(run func(context.Context, string) (*entities.User, error)) *UserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDriverUsers provides a mock function with given fields: ctx
func (_m *UserRepository) GetAllDriverUsers(ctx context.Context) ([]entities.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDriverUsers")
	}

	var r0 []entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetAllDriverUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDriverUsers'
type UserRepository_GetAllDriverUsers_Call struct {
	*mock.Call
}

// GetAllDriverUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepository_Expecter) GetAllDriverUsers(ctx interface{}) *UserRepository_GetAllDriverUsers_Call {
	return &UserRepository_GetAllDriverUsers_Call{Call: _e.mock.On("GetAllDriverUsers", ctx)}
}

func (_c *UserRepository_GetAllDriverUsers_Call) Run(run func(ctx context.Context)) *UserRepository_GetAllDriverUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserRepository_GetAllDriverUsers_Call) Return(_a0 []entities.User, _a1 error) *UserRepository_GetAllDriverUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetAllDriverUsers_Call) RunAndReturn(run func(context.Context) ([]entities.User, error)) *UserRepository_GetAllDriverUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
